# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "wait"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "kostis-codefresh/pipeline-per-branch"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-1"
    stage: "clone"

  waitForInputBeforeProduction:
    type: pending-approval
    stage: "wait"
    title: Deploy to Production?
    timeout:
      duration: 2
      finalState: denied

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "alpine:3.10.3" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - echo "Running in production"
      - cat README.md
    stage: "test"

